import {
  ItemConfig,
  HerbConfig,
  CraftingRecipe,
  MountConfig,
  Achievement,
  LevelInfo,
  BunnyState
} from './types';

export const BUNNY_STORAGE_KEY = 'ids_bunny_progress_v5';
export const MASCOT_SIZE = 80;

export const BUNNY_STATE_ROW_INDEX: Record<BunnyState, number> = {
  idle: 0,
  walk_right: 1,
  walk_left: 2,
  jump_right: 3,
  jump_left: 4,
  sleep: 5,
  eat: 6,
  run_right: 7,
  run_left: 8,
  dance: 9
};

export const RARITY_COLORS: Record<string, string> = {
  common:    '#93c5fd',
  uncommon:  '#86efac',
  rare:      '#f9a8d4',
  legendary: '#fde047',
  supreme:   '#c084fc'
};

export const ITEM_CONFIG: ItemConfig[] = [
  // ─── Nhóm Đan Dược Tăng Tu Vi (XP) ─────────────────────────────────────────
  { id: 'basic', name: 'Tụ Linh Đan', emoji: '💊', iconImage: '/items/01_tu_linh_dan.png', xpValue: 8, maxStack: 999, rarity: 'common', category: 'xp', buyPrice: 15, sellPrice: 6, description: '+8 Linh Lực (XP) • Nhận: tỉ lệ may mắn khi treo máy, kéo thả Thỏ, Lò Luyện Đan' },
  { id: 'recover', name: 'Hồi Phục Đan', emoji: '🍃', iconImage: '/items/02_hoi_phuc_dan.png', xpValue: 20, maxStack: 999, rarity: 'uncommon', category: 'xp', buyPrice: 40, sellPrice: 16, description: '+20 Linh Lực (XP) • Nhận: deploy thành công, Lò Luyện Đan Bát Quái' },
  { id: 'great', name: 'Đại Hoàn Đan', emoji: '🌸', iconImage: '/items/03_dai_hoan_dan.png', xpValue: 50, maxStack: 999, rarity: 'rare', category: 'xp', buyPrice: 90, sellPrice: 36, description: '+50 Linh Lực (XP) • Nhận: Độ Kiếp thành công, Lò Luyện Đan Bát Quái' },

  // ─── Nhóm Đan Dược Đột Phá Cảnh Giới (Đặc Thù Theo Cấp Bậc) ────────────────
  { id: 'pill_truc_co', name: 'Trúc Cơ Đan', emoji: '🌱', iconImage: '/items/05_truc_co_dan.png', xpValue: 20, maxStack: 99, rarity: 'uncommon', category: 'breakthrough', targetRealmIndex: 1, breakthroughBonus: 0.30, isBuff: true, buffDurationMs: 5 * 60 * 1000, buffSuccessBonus: 0.30, buyPrice: 120, sellPrice: 45, description: '+30% Tỉ lệ Đột phá Trúc Cơ (Lv.1 ➔ 2) & +20 XP • Chỉ dành cho cảnh giới Luyện Khí' },
  { id: 'pill_kim_dan', name: 'Kim Đan', emoji: '🟡', iconImage: '/items/06_kim_dan.png', xpValue: 40, maxStack: 99, rarity: 'rare', category: 'breakthrough', targetRealmIndex: 2, breakthroughBonus: 0.28, isBuff: true, buffDurationMs: 5 * 60 * 1000, buffSuccessBonus: 0.28, buyPrice: 260, sellPrice: 95, description: '+28% Tỉ lệ Ngưng Kết Kim Đan (Lv.2 ➔ 3) & +40 XP • Chỉ dành cho cảnh giới Trúc Cơ' },
  { id: 'pill_nguyen_anh', name: 'Nguyên Anh Đan', emoji: '👶', iconImage: '/items/07_nguyen_anh_dan.png', xpValue: 70, maxStack: 99, rarity: 'rare', category: 'breakthrough', targetRealmIndex: 3, breakthroughBonus: 0.25, isBuff: true, buffDurationMs: 5 * 60 * 1000, buffSuccessBonus: 0.25, buyPrice: 480, sellPrice: 180, description: '+25% Tỉ lệ Hóa Sinh Nguyên Anh (Lv.3 ➔ 4) & +70 XP • Chỉ dành cho cảnh giới Kim Đan' },
  { id: 'pill_hoa_than', name: 'Hóa Thần Đan', emoji: '🟣', iconImage: '/items/08_hoa_than_dan.png', xpValue: 120, maxStack: 99, rarity: 'legendary', category: 'breakthrough', targetRealmIndex: 4, breakthroughBonus: 0.24, isBuff: true, buffDurationMs: 6 * 60 * 1000, buffSuccessBonus: 0.24, buyPrice: 850, sellPrice: 320, description: '+24% Tỉ lệ Đột phá Hóa Thần (Lv.4 ➔ 5) & +120 XP • Chỉ dành cho cảnh giới Nguyên Anh' },
  { id: 'pill_luyen_hu', name: 'Luyện Hư Đan', emoji: '🌌', iconImage: '/items/09_luyen_hu_dan.png', xpValue: 180, maxStack: 99, rarity: 'legendary', category: 'breakthrough', targetRealmIndex: 5, breakthroughBonus: 0.22, isBuff: true, buffDurationMs: 6 * 60 * 1000, buffSuccessBonus: 0.22, buyPrice: 1300, sellPrice: 500, description: '+22% Tỉ lệ Đột phá Luyện Hư (Lv.5 ➔ 6) & +180 XP • Chỉ dành cho cảnh giới Hóa Thần' },
  { id: 'pill_hop_the', name: 'Hợp Thể Đan', emoji: '⚔️', iconImage: '/items/10_hop_the_dan.png', xpValue: 220, maxStack: 99, rarity: 'legendary', category: 'breakthrough', targetRealmIndex: 6, breakthroughBonus: 0.20, isBuff: true, buffDurationMs: 6 * 60 * 1000, buffSuccessBonus: 0.20, buyPrice: 1800, sellPrice: 700, description: '+20% Tỉ lệ Đột phá Hợp Thể (Lv.6 ➔ 7) & +220 XP • Chỉ dành cho cảnh giới Luyện Hư' },
  { id: 'pill_dai_thua', name: 'Đại Thừa Đan', emoji: '👑', iconImage: '/items/11_dai_thua_dan.png', xpValue: 260, maxStack: 99, rarity: 'legendary', category: 'breakthrough', targetRealmIndex: 7, breakthroughBonus: 0.20, isBuff: true, buffDurationMs: 8 * 60 * 1000, buffSuccessBonus: 0.20, buyPrice: 2200, sellPrice: 850, description: '+20% Tỉ lệ Đột phá Đại Thừa (Lv.7 ➔ 8) & +260 XP • Chỉ dành cho cảnh giới Hợp Thể' },
  { id: 'pill_do_kiep', name: 'Độ Kiếp Đan', emoji: '⚡', iconImage: '/items/12_do_kiep_dan.png', xpValue: 300, maxStack: 99, rarity: 'supreme', category: 'breakthrough', targetRealmIndex: 8, breakthroughBonus: 0.25, isBuff: true, buffDurationMs: 8 * 60 * 1000, buffSuccessBonus: 0.25, buyPrice: 2800, sellPrice: 1100, description: '+25% Tỉ lệ Độ Kiếp Lôi Kiếp (Lv.8 ➔ 9) & +300 XP • Chỉ dành cho cảnh giới Đại Thừa' },
  { id: 'pill_chan_tien', name: 'Chân Tiên Đan', emoji: '✨', iconImage: '/items/13_chan_tien_dan.png', xpValue: 450, maxStack: 99, rarity: 'supreme', category: 'breakthrough', targetRealmIndex: 9, breakthroughBonus: 0.18, isBuff: true, buffDurationMs: 10 * 60 * 1000, buffSuccessBonus: 0.18, buyPrice: 4000, sellPrice: 1600, description: '+18% Tỉ lệ Phi Thăng Chân Tiên (Lv.9 ➔ 10) & +450 XP • Chỉ dành cho cảnh giới Độ Kiếp' },
  { id: 'pill_huyen_tien', name: 'Huyền Tiên Đan', emoji: '💫', iconImage: '/items/14_huyen_tien_dan.png', xpValue: 550, maxStack: 99, rarity: 'supreme', category: 'breakthrough', targetRealmIndex: 10, breakthroughBonus: 0.18, isBuff: true, buffDurationMs: 10 * 60 * 1000, buffSuccessBonus: 0.18, buyPrice: 5000, sellPrice: 2000, description: '+18% Tỉ lệ Đột phá Huyền Tiên (Lv.10 ➔ 11) & +550 XP • Chỉ dành cho cảnh giới Chân Tiên' },
  { id: 'pill_kim_tien', name: 'Kim Tiên Đan', emoji: '🏆', iconImage: '/items/15_kim_tien_dan.png', xpValue: 650, maxStack: 99, rarity: 'supreme', category: 'breakthrough', targetRealmIndex: 11, breakthroughBonus: 0.18, isBuff: true, buffDurationMs: 10 * 60 * 1000, buffSuccessBonus: 0.18, buyPrice: 6000, sellPrice: 2400, description: '+18% Tỉ lệ Đột phá Kim Tiên (Lv.11 ➔ 12) & +650 XP • Chỉ dành cho cảnh giới Huyền Tiên' },
  { id: 'pill_thai_at', name: 'Thái Ất Kim Đan', emoji: '👑', iconImage: '/items/16_thai_at_kim_dan.png', xpValue: 800, maxStack: 99, rarity: 'supreme', category: 'breakthrough', targetRealmIndex: 12, breakthroughBonus: 0.16, isBuff: true, buffDurationMs: 10 * 60 * 1000, buffSuccessBonus: 0.16, buyPrice: 7500, sellPrice: 3000, description: '+16% Tỉ lệ Đột phá Thái Ất Ngọc Tiên (Lv.12 ➔ 13) & +800 XP • Chỉ dành cho Kim Tiên' },
  { id: 'pill_thai_at_kim', name: 'Thái Ất Thần Đan', emoji: '🔱', iconImage: '/items/20_thai_at_than_dan.png', xpValue: 950, maxStack: 99, rarity: 'supreme', category: 'breakthrough', targetRealmIndex: 13, breakthroughBonus: 0.16, isBuff: true, buffDurationMs: 10 * 60 * 1000, buffSuccessBonus: 0.16, buyPrice: 9000, sellPrice: 3600, description: '+16% Tỉ lệ Đột phá Thái Ất Kim Tiên (Lv.13 ➔ 14) & +950 XP • Chỉ dành cho Thái Ất Ngọc Tiên' },
  { id: 'pill_dai_la', name: 'Đại La Đan', emoji: '🌌', iconImage: '/items/21_dai_la_dan.png', xpValue: 1200, maxStack: 99, rarity: 'supreme', category: 'breakthrough', targetRealmIndex: 14, breakthroughBonus: 0.15, isBuff: true, buffDurationMs: 10 * 60 * 1000, buffSuccessBonus: 0.15, buyPrice: 12000, sellPrice: 4800, description: '+15% Tỉ lệ Đột phá Đại La Kim Tiên (Lv.14 ➔ 15) & +1200 XP • Chỉ dành cho Thái Ất Kim Tiên' },
  { id: 'pill_hon_nguyen', name: 'Hỗn Nguyên Đan', emoji: '☯️', iconImage: '/items/22_hon_nguyen_dan.png', xpValue: 1500, maxStack: 99, rarity: 'supreme', category: 'breakthrough', targetRealmIndex: 15, breakthroughBonus: 0.15, isBuff: true, buffDurationMs: 10 * 60 * 1000, buffSuccessBonus: 0.15, buyPrice: 15000, sellPrice: 6000, description: '+15% Tỉ lệ Đột phá Hỗn Nguyên Đại La (Lv.15 ➔ 16) & +1500 XP • Chỉ dành cho Đại La Kim Tiên' },
  { id: 'pill_tien_de', name: 'Tiên Đế Đan', emoji: '👑', iconImage: '/items/23_tien_de_dan.png', xpValue: 2000, maxStack: 99, rarity: 'supreme', category: 'breakthrough', targetRealmIndex: 16, breakthroughBonus: 0.15, isBuff: true, buffDurationMs: 10 * 60 * 1000, buffSuccessBonus: 0.15, buyPrice: 20000, sellPrice: 8000, description: '+15% Tỉ lệ Đột phá Tiên Đế Chí Tôn (Lv.16 ➔ 17) & +2000 XP • Chỉ dành cho Hỗn Nguyên Đại La' },

  // ─── Nhóm Đan Dược Buff Đặc Biệt & Hộ Mệnh ───────────────────────────────
  { id: 'pill_ngo_dao', name: 'Ngộ Đạo Đan', emoji: '🧘', iconImage: '/items/50_ngo_dao_dan.png', xpValue: 30, maxStack: 99, rarity: 'rare', category: 'buff', isBuff: true, buffDurationMs: 15 * 60 * 1000, expMultiplier: 2.0, buyPrice: 450, sellPrice: 170, description: 'x2 Tốc độ nhận Linh Lực (XP) khi treo máy & click Thỏ trong 15 phút' },
  { id: 'pill_thien_dao', name: 'Thiên Đạo Đan', emoji: '🌟', iconImage: '/items/51_thien_dao_dan.png', xpValue: 50, maxStack: 99, rarity: 'legendary', category: 'buff', isBuff: true, buffDurationMs: 15 * 60 * 1000, dropRateMultiplier: 1.5, buyPrice: 850, sellPrice: 330, description: '+50% Tỉ lệ may mắn rơi Thảo Dược & Quặng Hiếm trong 15 phút' },
  { id: 'pill_vo_cuc', name: 'Vô Cực Đan', emoji: '☯️', iconImage: '/items/52_vo_cuc_dan.png', xpValue: 100, maxStack: 99, rarity: 'supreme', category: 'buff', isBuff: true, buffDurationMs: 10 * 60 * 1000, buffSuccessBonus: 0.20, forgeSuccessBonus: 0.20, buyPrice: 1800, sellPrice: 700, description: 'Âm Dương Hỗ Trợ: +20% Tỉ lệ Độ Kiếp & +20% Tỉ lệ Rèn Pháp Bảo trong 10 phút' },
  { id: 'talisman', name: 'Hộ Kiếp Phù', emoji: '🔱', iconImage: '/items/17_ho_kiep_phu.png', xpValue: 0, maxStack: 99, rarity: 'legendary', category: 'breakthrough', isBuff: true, buffDurationMs: 5 * 60 * 1000, buffSuccessBonus: 0.25, buyPrice: 600, sellPrice: 240, description: '+25% Tỉ lệ Độ Kiếp trong 5 phút • Luyện từ Lò Bát Quái' },
  { id: 'revive', name: 'Cửu Chuyển Hoàn Hồn Đan', emoji: '🔮', iconImage: '/items/04_cuu_chuyen_hoan_hon_dan.png', xpValue: 100, maxStack: 99, rarity: 'supreme', category: 'breakthrough', isBuff: true, buffDurationMs: 10 * 60 * 1000, buffSuccessBonus: 0.35, buyPrice: 1500, sellPrice: 600, description: '+35% Tỉ lệ Độ Kiếp & Bảo hộ 100% không tổn hại XP khi thất bại (10 phút)' },

  // ─── Nhóm Phụ Trợ Rèn Pháp Bảo ───────────────────────────────────────────
  { id: 'forge_talisman', name: 'Thần Luyện Phù', emoji: '📜', iconImage: '/items/18_than_luyen_phu.png', xpValue: 0, maxStack: 99, rarity: 'legendary', category: 'forge', isForgeBooster: true, forgeSuccessBonus: 0.20, buyPrice: 400, sellPrice: 150, description: '+20% Tỉ lệ rèn Pháp Bảo / lần rèn • Luyện từ Lò Bát Quái, Gacha hoặc Phường Thị' },
  { id: 'sky_stone', name: 'Bổ Thiên Thần Thạch', emoji: '💠', iconImage: '/items/25_bo_thien_thach.png', xpValue: 0, maxStack: 99, rarity: 'supreme', category: 'forge', isForgeBooster: true, forgeSuccessBonus: 0.35, refundOnFailRatio: 0.50, buyPrice: 1200, sellPrice: 480, description: '+35% Tỉ lệ rèn Pháp Bảo / lần rèn & Hoàn 50% Linh Thạch nếu xịt' }
];

export const HERB_CONFIG: HerbConfig[] = [
  { id: 'herb_lingzhi',        name: 'Linh Tuyền Thảo',      emoji: '🌿', iconImage: '/materials/01_linh_tuyen_thao.png',       rarity: 'common',    dropChance: 0.12,  buyPrice: 20,   sellPrice: 8,   description: 'Thảo dược ven bờ linh tuyền hấp thụ khí cơ (Tỉ lệ rớt 12%/phút)' },
  { id: 'herb_ginseng',        name: 'Bách Niên Nhân Sâm',  emoji: '🪵', iconImage: '/materials/02_bach_nien_nhan_sam.png',     rarity: 'common',    dropChance: 0.10,  buyPrice: 25,   sellPrice: 10,  description: 'Nhân sâm trăm tuổi hút linh khí đất trời (Tỉ lệ rớt 10%/phút)' },
  { id: 'mineral_iron',        name: 'Huyền Thiết Quặng',    emoji: '🪨', iconImage: '/materials/29_huyen_thiet_quang.png',     rarity: 'common',    dropChance: 0.09,  buyPrice: 30,   sellPrice: 12,  description: 'Quặng sắt linh khí chứa hắc kim cổ xưa (Tỉ lệ rớt 9%/phút)' },
  { id: 'herb_lotus',          name: 'Cửu Phẩm Băng Liên',   emoji: '🪷', iconImage: '/materials/47_cuu_pham_bang_lien.png',    rarity: 'uncommon',  dropChance: 0.07,  buyPrice: 65,   sellPrice: 26,  description: 'Băng liên sen tuyết ngàn năm trên đỉnh tuyết sơn (Tỉ lệ rớt 7%/phút)' },
  { id: 'herb_fire_fruit',     name: 'Xích Diệm Hỏa Quả',   emoji: '🍎', iconImage: '/materials/19_xich_diem_hoa_qua.png',      rarity: 'uncommon',  dropChance: 0.06,  buyPrice: 75,   sellPrice: 30,  description: 'Hỏa quả ngưng tụ từ cực dương hỏa (Tỉ lệ rớt 6%/phút)' },
  { id: 'mineral_crystal',     name: 'Thạch Anh Linh Tinh',  emoji: '💎', iconImage: '/materials/07_thach_anh_linh_tinh.png',   rarity: 'uncommon',  dropChance: 0.05,  buyPrice: 90,   sellPrice: 36,  description: 'Tinh thể ngọc bích phát sáng linh quang (Tỉ lệ rớt 5%/phút)' },
  { id: 'herb_bamboo',         name: 'Ninh Sương Trúc Chồi', emoji: '🎍', iconImage: '/materials/03_ninh_suong_truc_choi.png',  rarity: 'rare',      dropChance: 0.035, buyPrice: 180,  sellPrice: 70,  description: 'Trúc tiên đọng sương mai lúc rạng đông (Tỉ lệ rớt 3.5%/phút)' },
  { id: 'herb_dragon_grass',   name: 'Long Kế Thảo',        emoji: '🐉', iconImage: '/materials/13_long_ke_thao.png',           rarity: 'rare',      dropChance: 0.025, buyPrice: 240,  sellPrice: 95,  description: 'Cỏ thiêng thấm huyết mạch linh long (Tỉ lệ rớt 2.5%/phút)' },
  { id: 'mineral_gold',        name: 'Thái Cổ Kim Tinh',    emoji: '🌟', iconImage: '/materials/30_thai_co_kim_tinh.png',       rarity: 'rare',      dropChance: 0.02,  buyPrice: 320,  sellPrice: 125, description: 'Tinh quặng vàng Thái Cổ chói lọi (Tỉ lệ rớt 2%/phút)' },
  { id: 'herb_phoenix_flower', name: 'Phượng Hoàng Hỏa Hoa', emoji: '🌺', iconImage: '/materials/28_phuong_hoang_hoa_hoa.png',  rarity: 'legendary', dropChance: 0.01,  buyPrice: 700,  sellPrice: 280, description: 'Hoa lửa thần phượng tắm từ biển lửa (Tỉ lệ rớt 1%/phút)' },
  { id: 'mineral_star_stone',  name: 'Cửu Thiên Tinh Thạch', emoji: '🌌', iconImage: '/materials/32_cuu_thien_tinh_thach.png',   rarity: 'legendary', dropChance: 0.007, buyPrice: 1000, sellPrice: 400, description: 'Đá thiên thạch rơi từ cửu trùng thiên (Tỉ lệ rớt 0.7%/phút)' },
  { id: 'herb_immortal_root',  name: 'Hỗn Nguyên Thần Căn',  emoji: '👑', iconImage: '/materials/48_hon_nguyen_than_can.png',   rarity: 'supreme',   dropChance: 0.003, buyPrice: 2400, sellPrice: 950, description: 'Rễ cây thần Thái Cổ thuở khai thiên lập địa (Tỉ lệ rớt 0.3%/phút)' }
];

export const CRAFTING_RECIPES: CraftingRecipe[] = [
  // ─── Công thức Tăng Tu Vi ────────────────────────────────────────────────
  {
    id: 'craft_basic',
    name: 'Luyện Tụ Linh Đan',
    emoji: '💊',
    iconImage: '/items/01_tu_linh_dan.png',
    resultItemId: 'basic',
    resultAmount: 2,
    category: 'xp',
    ingredients: [{ id: 'herb_lingzhi', amount: 2 }, { id: 'herb_ginseng', amount: 1 }],
    spiritStonesCost: 10,
    successRate: 0.98,
    description: 'Chế tạo 2x Tụ Linh Đan (+16 XP) từ 2x Linh Tuyền Thảo + 1x Bách Niên Nhân Sâm & 10 Linh Thạch (Thành công 98%).',
    rarity: 'common'
  },
  {
    id: 'craft_recover',
    name: 'Luyện Hồi Phục Đan',
    emoji: '🍃',
    iconImage: '/items/02_hoi_phuc_dan.png',
    resultItemId: 'recover',
    resultAmount: 2,
    category: 'xp',
    ingredients: [{ id: 'herb_lotus', amount: 2 }, { id: 'herb_fire_fruit', amount: 2 }, { id: 'mineral_iron', amount: 1 }],
    spiritStonesCost: 25,
    successRate: 0.90,
    description: 'Chế tạo 2x Hồi Phục Đan (+40 XP) từ 2x Cửu Phẩm Băng Liên + 2x Xích Diệm Hỏa Quả + 1x Huyền Thiết Quặng & 25 Linh Thạch (Thành công 90%).',
    rarity: 'uncommon'
  },
  {
    id: 'craft_great',
    name: 'Luyện Đại Hoàn Đan',
    emoji: '🌸',
    iconImage: '/items/03_dai_hoan_dan.png',
    resultItemId: 'great',
    resultAmount: 1,
    category: 'xp',
    ingredients: [{ id: 'herb_dragon_grass', amount: 2 }, { id: 'herb_bamboo', amount: 2 }, { id: 'mineral_gold', amount: 1 }],
    spiritStonesCost: 50,
    successRate: 0.85,
    description: 'Chế tạo 1x Đại Hoàn Đan (+50 XP) từ 2x Long Kế Thảo + 2x Ninh Sương Trúc Chồi + 1x Thái Cổ Kim Tinh & 50 Linh Thạch (Thành công 85%).',
    rarity: 'rare'
  },

  // ─── Công thức Đột Phá Cảnh Giới ─────────────────────────────────────────
  {
    id: 'craft_pill_truc_co',
    name: 'Luyện Trúc Cơ Đan',
    emoji: '🌱',
    iconImage: '/items/05_truc_co_dan.png',
    resultItemId: 'pill_truc_co',
    resultAmount: 1,
    category: 'breakthrough',
    ingredients: [{ id: 'herb_lingzhi', amount: 3 }, { id: 'herb_ginseng', amount: 2 }, { id: 'mineral_crystal', amount: 1 }],
    spiritStonesCost: 40,
    successRate: 0.92,
    description: 'Luyện Trúc Cơ Đan (+30% Đột phá Trúc Cơ) từ 3x Linh Tuyền Thảo + 2x Bách Niên Nhân Sâm + 1x Thạch Anh Linh Tinh & 40 Linh Thạch.',
    rarity: 'uncommon'
  },
  {
    id: 'craft_pill_kim_dan',
    name: 'Luyện Kim Đan',
    emoji: '🟡',
    iconImage: '/items/06_kim_dan.png',
    resultItemId: 'pill_kim_dan',
    resultAmount: 1,
    category: 'breakthrough',
    ingredients: [{ id: 'herb_bamboo', amount: 2 }, { id: 'mineral_gold', amount: 2 }, { id: 'herb_fire_fruit', amount: 2 }],
    spiritStonesCost: 80,
    successRate: 0.85,
    description: 'Luyện Kim Đan (+25% Đột phá Kim Đan) từ 2x Ninh Sương Trúc Chồi + 2x Thái Cổ Kim Tinh + 2x Xích Diệm Hỏa Quả & 80 Linh Thạch.',
    rarity: 'rare'
  },
  {
    id: 'craft_pill_nguyen_anh',
    name: 'Luyện Nguyên Anh Đan',
    emoji: '👶',
    iconImage: '/items/07_nguyen_anh_dan.png',
    resultItemId: 'pill_nguyen_anh',
    resultAmount: 1,
    category: 'breakthrough',
    ingredients: [{ id: 'herb_dragon_grass', amount: 3 }, { id: 'herb_lotus', amount: 3 }, { id: 'mineral_gold', amount: 2 }],
    spiritStonesCost: 150,
    successRate: 0.80,
    description: 'Luyện Nguyên Anh Đan (+25% Đột phá Nguyên Anh) từ 3x Long Kế Thảo + 3x Cửu Phẩm Băng Liên + 2x Thái Cổ Kim Tinh & 150 Linh Thạch.',
    rarity: 'rare'
  },
  {
    id: 'craft_pill_hoa_than',
    name: 'Luyện Hóa Thần Đan',
    emoji: '🟣',
    iconImage: '/items/08_hoa_than_dan.png',
    resultItemId: 'pill_hoa_than',
    resultAmount: 1,
    category: 'breakthrough',
    ingredients: [{ id: 'herb_phoenix_flower', amount: 2 }, { id: 'mineral_star_stone', amount: 2 }, { id: 'herb_dragon_grass', amount: 2 }],
    spiritStonesCost: 300,
    successRate: 0.75,
    description: 'Luyện Hóa Thần Đan (+20% Đột phá Hóa Thần) từ 2x Phượng Hoàng Hỏa Hoa + 2x Cửu Thiên Tinh Thạch + 2x Long Kế Thảo & 300 Linh Thạch.',
    rarity: 'legendary'
  },
  {
    id: 'craft_pill_do_kiep',
    name: 'Luyện Độ Kiếp Đan',
    emoji: '⚡',
    iconImage: '/items/12_do_kiep_dan.png',
    resultItemId: 'pill_do_kiep',
    resultAmount: 1,
    category: 'breakthrough',
    ingredients: [{ id: 'herb_immortal_root', amount: 2 }, { id: 'mineral_star_stone', amount: 3 }, { id: 'herb_phoenix_flower', amount: 3 }],
    spiritStonesCost: 600,
    successRate: 0.70,
    description: 'Luyện Độ Kiếp Đan (+25% Vượt Lôi Kiếp) từ 2x Hỗn Nguyên Thần Căn + 3x Cửu Thiên Tinh Thạch + 3x Phượng Hoàng Hỏa Hoa & 600 Linh Thạch.',
    rarity: 'supreme'
  },
  {
    id: 'craft_pill_chan_tien',
    name: 'Luyện Chân Tiên Đan',
    emoji: '✨',
    iconImage: '/items/13_chan_tien_dan.png',
    resultItemId: 'pill_chan_tien',
    resultAmount: 1,
    category: 'breakthrough',
    ingredients: [{ id: 'herb_immortal_root', amount: 3 }, { id: 'mineral_star_stone', amount: 4 }, { id: 'herb_lotus', amount: 5 }],
    spiritStonesCost: 1000,
    successRate: 0.65,
    description: 'Chí Bảo Tiên Giới: Luyện Chân Tiên Đan (+18% Đột phá Tiên Nhân) từ 3x Hỗn Nguyên Thần Căn + 4x Cửu Thiên Tinh Thạch + 5x Băng Liên & 1000 Linh Thạch.',
    rarity: 'supreme'
  },

  // ─── Công thức Đạo Cảnh Buff & Phụ Trợ ──────────────────────────────────
  {
    id: 'craft_pill_ngo_dao',
    name: 'Luyện Ngộ Đạo Đan',
    emoji: '🧘',
    iconImage: '/items/50_ngo_dao_dan.png',
    resultItemId: 'pill_ngo_dao',
    resultAmount: 1,
    category: 'buff',
    ingredients: [{ id: 'herb_bamboo', amount: 3 }, { id: 'herb_ginseng', amount: 3 }, { id: 'mineral_crystal', amount: 2 }],
    spiritStonesCost: 120,
    successRate: 0.85,
    description: 'Luyện Ngộ Đạo Đan (x2 XP trong 15 phút) từ 3x Ninh Sương Trúc Chồi + 3x Bách Niên Nhân Sâm + 2x Thạch Anh Linh Tinh & 120 Linh Thạch.',
    rarity: 'rare'
  },
  {
    id: 'craft_pill_thien_dao',
    name: 'Luyện Thiên Đạo Đan',
    emoji: '🌟',
    iconImage: '/items/51_thien_dao_dan.png',
    resultItemId: 'pill_thien_dao',
    resultAmount: 1,
    category: 'buff',
    ingredients: [{ id: 'herb_phoenix_flower', amount: 2 }, { id: 'herb_dragon_grass', amount: 3 }, { id: 'mineral_gold', amount: 2 }],
    spiritStonesCost: 250,
    successRate: 0.80,
    description: 'Luyện Thiên Đạo Đan (+50% May mắn rơi nguyên liệu hiếm trong 15 phút) từ 2x Phượng Hoàng Hỏa Hoa + 3x Long Kế Thảo + 2x Thái Cổ Kim Tinh & 250 Linh Thạch.',
    rarity: 'legendary'
  },
  {
    id: 'craft_pill_vo_cuc',
    name: 'Luyện Vô Cực Đan',
    emoji: '☯️',
    iconImage: '/items/52_vo_cuc_dan.png',
    resultItemId: 'pill_vo_cuc',
    resultAmount: 1,
    category: 'buff',
    ingredients: [{ id: 'herb_immortal_root', amount: 2 }, { id: 'herb_lotus', amount: 4 }, { id: 'mineral_gold', amount: 3 }],
    spiritStonesCost: 450,
    successRate: 0.75,
    description: 'Luyện Vô Cực Đan (+20% Đột Phá & +20% Rèn Pháp Bảo trong 10 phút) từ 2x Hỗn Nguyên Thần Căn + 4x Băng Liên + 3x Thái Cổ Kim Tinh & 450 Linh Thạch.',
    rarity: 'supreme'
  },
  {
    id: 'craft_talisman',
    name: 'Luyện Hộ Kiếp Phù',
    emoji: '🔱',
    iconImage: '/items/17_ho_kiep_phu.png',
    resultItemId: 'talisman',
    resultAmount: 1,
    category: 'breakthrough',
    ingredients: [{ id: 'herb_phoenix_flower', amount: 2 }, { id: 'mineral_star_stone', amount: 1 }],
    spiritStonesCost: 100,
    successRate: 0.75,
    description: 'Chế tạo 1x Hộ Kiếp Phù (+25% Độ Kiếp) từ 2x Phượng Hoàng Hỏa Hoa + 1x Cửu Thiên Tinh Thạch & 100 Linh Thạch (Thành công 75%).',
    rarity: 'legendary'
  },
  {
    id: 'craft_revive',
    name: 'Cửu Chuyển Hoàn Hồn Đan',
    emoji: '🔮',
    iconImage: '/items/04_cuu_chuyen_hoan_hon_dan.png',
    resultItemId: 'revive',
    resultAmount: 1,
    category: 'breakthrough',
    ingredients: [{ id: 'herb_immortal_root', amount: 2 }, { id: 'mineral_star_stone', amount: 2 }, { id: 'herb_phoenix_flower', amount: 2 }],
    spiritStonesCost: 200,
    successRate: 0.65,
    description: 'Đan Cực Phẩm! Bảo hộ 100% không tổn hại XP khi Độ Kiếp thất bại & +35% Tỉ lệ Độ Kiếp từ 2x Hỗn Nguyên Thần Căn + 2x Cửu Thiên Tinh Thạch + 2x Phượng Hoàng Hỏa Hoa & 200 Linh Thạch (Thành công 65%).',
    rarity: 'supreme'
  },
  {
    id: 'craft_forge_talisman',
    name: 'Luyện Thần Luyện Phù',
    emoji: '📜',
    iconImage: '/items/18_than_luyen_phu.png',
    resultItemId: 'forge_talisman',
    resultAmount: 1,
    category: 'forge',
    ingredients: [{ id: 'mineral_iron', amount: 2 }, { id: 'mineral_crystal', amount: 2 }, { id: 'mineral_gold', amount: 1 }],
    spiritStonesCost: 75,
    successRate: 0.80,
    description: 'Chế tạo 1x Thần Luyện Phù (+20% Tỉ lệ Rèn Pháp Bảo / lần rèn) từ 2x Huyền Thiết Quặng + 2x Thạch Anh Linh Tinh + 1x Thái Cổ Kim Tinh & 75 Linh Thạch (Thành công 80%).',
    rarity: 'legendary'
  },
  {
    id: 'craft_sky_stone',
    name: 'Luyện Bổ Thiên Thạch',
    emoji: '💠',
    iconImage: '/items/25_bo_thien_thach.png',
    resultItemId: 'sky_stone',
    resultAmount: 1,
    category: 'forge',
    ingredients: [{ id: 'mineral_star_stone', amount: 2 }, { id: 'herb_immortal_root', amount: 1 }, { id: 'mineral_gold', amount: 2 }],
    spiritStonesCost: 150,
    successRate: 0.70,
    description: 'Thần Thạch Bổ Thiên Cực Phẩm! Gia tăng +35% Tỉ lệ Rèn Pháp Bảo / lần rèn & hoàn 50% Linh Thạch khi thất bại từ 2x Cửu Thiên Tinh Thạch + 1x Hỗn Nguyên Thần Căn + 2x Thái Cổ Kim Tinh & 150 Linh Thạch (Thành công 70%).',
    rarity: 'supreme'
  }
];

export const MOUNT_CONFIG: MountConfig[] = [
  {
    id: 'wolf',
    name: 'Thanh Phong Linh Lang',
    species: 'Spirit Wolf',
    element: 'Wind 🌪️',
    emoji: '🐺',
    spriteFile: 'thanh_phong_lang.png',
    rarity: 'common',
    dragXpBonus: 5,
    dropRate: 8.0,
    buffName: 'Tật Phong Thần Hành',
    buffDescription: '+5 XP / lần kéo thả Thỏ',
    description: 'Bạch lang cuộn vầng phong khí, phi hành nhanh như chớp lốc.',
    auraColor: '#38bdf8',
    elementParticles: ['💨', '🌀', '✨']
  },
  {
    id: 'deer',
    name: 'Ngọc Linh Lộc',
    species: 'Jade Spirit Deer',
    element: 'Nature 🍃',
    emoji: '🦌',
    spriteFile: 'ngoc_linh_loc.png',
    rarity: 'common',
    dragXpBonus: 8,
    dropRate: 6.0,
    buffName: 'Mộc Linh Dưỡng Tâm',
    buffDescription: '+8 XP / lần kéo & Bồ đề dưỡng khí',
    description: 'Hươu tiên sừng ngọc lục bảo tỏa ánh thuần thanh linh khí.',
    auraColor: '#4ade80',
    elementParticles: ['🍃', '🌿', '✨']
  },
  {
    id: 'tiger',
    name: 'Kim Văn Linh Hổ',
    species: 'Golden Spirit Tiger',
    element: 'Earth 🌾',
    emoji: '🐯',
    spriteFile: 'kim_van_ho.png',
    rarity: 'uncommon',
    dragXpBonus: 12,
    dropRate: 4.0,
    buffName: 'Kim Cương Bạt Nhụy',
    buffDescription: '+12 XP / kéo & Triển khai Đan Điền gia tăng',
    description: 'Thần hổ mang bạch kim văn, khí tức dạt dào thối luyện đan điền.',
    auraColor: '#fbbf24',
    elementParticles: ['✨', '🔥', '🌾']
  },
  {
    id: 'fox',
    name: 'Cửu Vĩ Linh Hồ',
    species: 'Nine-Tailed Celestial Fox',
    element: 'Spirit 🔮',
    emoji: '🦊',
    spriteFile: 'cuu_vi_ho.png',
    rarity: 'uncommon',
    dragXpBonus: 15,
    dropRate: 2.5,
    buffName: 'Cửu Vĩ Âm Dương',
    buffDescription: '+15 XP / kéo & Tăng +3% Tỉ lệ Độ Kiếp vĩnh viễn',
    breakthroughBonus: 0.03,
    description: 'Cáo chín đuôi bồng bềnh hoa nguyệt, ảo mộng tam giới.',
    auraColor: '#c084fc',
    elementParticles: ['🔮', '💜', '✨']
  },
  {
    id: 'dragon_azure',
    name: 'Thanh Vân Giao Long',
    species: 'Azure Chinese Dragon',
    element: 'Water & Cloud 🌊',
    emoji: '🐲',
    spriteFile: 'thanh_lan_long.png',
    rarity: 'rare',
    dragXpBonus: 20,
    dropRate: 1.5,
    buffName: 'Long Vực Cam Lồ',
    buffDescription: '+20 XP / kéo & Gia trì 15% Đan Dược thần hiệu',
    description: 'Thần long mình xanh ngọc uốn lượn cưỡi mây đạp sóng.',
    auraColor: '#06b6d4',
    elementParticles: ['🌊', '💧', '☁️']
  },
  {
    id: 'eagle',
    name: 'Tử Điện Lôi Ưng',
    species: 'Thunder Eagle',
    element: 'Lightning ⚡',
    emoji: '🦅',
    spriteFile: 'tu_dien_loi_ung.png',
    rarity: 'rare',
    dragXpBonus: 25,
    dropRate: 1.0,
    buffName: 'Cuồng Lôi Thối Thể',
    buffDescription: '+25 XP / kéo & Tăng +5% Tỉ lệ Độ Kiếp thành công',
    breakthroughBonus: 0.05,
    description: 'Đại ưng cuồng lôi cánh tím, xé rách tầng mây giáng lôi đình.',
    auraColor: '#a855f7',
    elementParticles: ['⚡', '🌩️', '💜']
  },
  {
    id: 'horse',
    name: 'Thiên Lý Long Mã',
    species: 'Celestial Dragon Horse',
    element: 'Heavenly Wind 🌤️',
    emoji: '🐴',
    spriteFile: 'thien_ma_tinh_van.png',
    rarity: 'legendary',
    dragXpBonus: 30,
    dropRate: 0.5,
    buffName: 'Súc Địa Thành Thốn',
    buffDescription: '+30 XP / kéo & Multi-deploy nhận X2 Linh Lực',
    description: 'Long mã sừng rồng vảy vàng, vó đạp thái dương khí.',
    auraColor: '#fef08a',
    elementParticles: ['🌤️', '✨', '⚡']
  },
  {
    id: 'turtle',
    name: 'Huyền Vũ Linh Quy',
    species: 'Sacred Black Tortoise',
    element: 'Defense & Water 🛡️',
    emoji: '🐢',
    spriteFile: 'huyen_vu_linh_quy.png',
    rarity: 'legendary',
    dragXpBonus: 35,
    dropRate: 0.35,
    buffName: 'Huyền Vũ Hộ Tâm',
    buffDescription: '+35 XP / kéo & Tăng +8% Tỉ lệ Độ Kiếp & Bảo hộ kinh mạch',
    breakthroughBonus: 0.08,
    description: 'Linh quy mang mai Bát Quái, rắn tiên cuộn quanh bất tử.',
    auraColor: '#3b82f6',
    elementParticles: ['🛡️', '☯️', '🌊']
  },
  {
    id: 'dragon_thunder',
    name: 'Cửu Thiên Lôi Long',
    species: 'Heavenly Thunder Dragon',
    element: 'Celestial Thunder 🌩️',
    emoji: '🐉',
    spriteFile: 'thai_co_chien_ky_lan.png',
    rarity: 'supreme',
    dragXpBonus: 45,
    dropRate: 0.15,
    buffName: 'Cửu Trùng Thiên Kiếp',
    buffDescription: '+45 XP / kéo & Tăng hẳn +12% Tỉ lệ Độ Kiếp vĩnh viễn',
    breakthroughBonus: 0.12,
    description: 'Thượng cổ Lôi Long vảy lam thẫm gia trì cửu trùng thiên kiếp.',
    auraColor: '#eab308',
    elementParticles: ['⚡', '🌩️', '🔥']
  },
  {
    id: 'qilin',
    name: 'Bạch Ngọc Kỳ Lân',
    species: 'Celestial Qilin',
    element: 'Divine Blessing ☯️',
    emoji: '🦄',
    spriteFile: 'ky_lan_ngu_sac.png',
    rarity: 'supreme',
    dragXpBonus: 50,
    dropRate: 0.08,
    buffName: 'Vạn Cổ Hồng Hoang',
    buffDescription: '+50 XP / kéo & Tăng +15% Tỉ lệ Độ Kiếp & Phúc duyên vô lượng',
    breakthroughBonus: 0.15,
    description: 'Kỳ Lân bồ đề tỏa liên hoa ngát hương, công đức vô lượng.',
    auraColor: '#2dd4bf',
    elementParticles: ['☯️', '🌸', '✨']
  }
];

export const LEVEL_CONFIG: LevelInfo[] = [
  { level: 1,  name: 'Luyện Khí Kỳ',           reqXp: 0,      skinId: 'none',      skinName: 'Mộc Linh Kiếm',        treasureId: 1 },
  { level: 2,  name: 'Trúc Cơ Kỳ',              reqXp: 100,    skinId: 'grad_cap',  skinName: 'Tụ Linh Phù',          treasureId: 2 },
  { level: 3,  name: 'Kim Đan Kỳ',              reqXp: 300,    skinId: 'cap',       skinName: 'Kim Đan Phi Kiếm',      treasureId: 3 },
  { level: 4,  name: 'Nguyên Anh Kỳ',           reqXp: 700,    skinId: 'helmet',    skinName: 'Nguyên Anh Liên Đài',  treasureId: 4 },
  { level: 5,  name: 'Hóa Thần Kỳ',             reqXp: 1500,   skinId: 'astro',     skinName: 'Hóa Thần Linh Trượng', treasureId: 5 },
  { level: 6,  name: 'Luyện Hư Kỳ',             reqXp: 3000,   skinId: 'glasses',   skinName: 'Hư Không Luân',        treasureId: 6 },
  { level: 7,  name: 'Hợp Thể Kỳ',              reqXp: 5500,   skinId: 'ninja',     skinName: 'Thiên Đạo Thương',     treasureId: 7 },
  { level: 8,  name: 'Đại Thừa Kỳ',             reqXp: 9000,   skinId: 'crown',     skinName: 'Bát Quái Kính',        treasureId: 8 },
  { level: 9,  name: 'Độ Kiếp Kỳ',              reqXp: 14000,  skinId: 'aura',      skinName: 'Cửu Thiên Lôi Ấn',     treasureId: 9 },
  { level: 10, name: 'Chân Tiên',               reqXp: 20000,  skinId: 'chan_tien', skinName: 'Bồ Đề Thần Thụ',      treasureId: 10 },
  { level: 11, name: 'Huyền Tiên',              reqXp: 28000,  skinId: 'huyen_tien',skinName: 'Huyền Thiên Đạo Luân',treasureId: 11 },
  { level: 12, name: 'Kim Tiên',                reqXp: 38000,  skinId: 'kim_tien',  skinName: 'Kim Tiên Đế Ấn',      treasureId: 12 },
  { level: 13, name: 'Thái Ất Ngọc Tiên',       reqXp: 50000,  skinId: 'ngoc_tien', skinName: 'Thái Ất Ngọc Hồ',     treasureId: 13 },
  { level: 14, name: 'Thái Ất Kim Tiên',         reqXp: 65000,  skinId: 'thai_at',  skinName: 'Thái Ất Thần Kích',    treasureId: 14 },
  { level: 15, name: 'Đại La Kim Tiên',          reqXp: 85000,  skinId: 'dai_la',   skinName: 'Vạn Giới Thiên Luân', treasureId: 15 },
  { level: 16, name: 'Hỗn Nguyên Đại La',      reqXp: 110000, skinId: 'hon_nguyen',skinName: 'Hỗn Nguyên Đạo Đỉnh',  treasureId: 16 },
  { level: 17, name: 'Thánh Nhân (Tiên Đế)',  reqXp: 150000, skinId: 'god',      skinName: 'Vạn Giới Đạo Bảo',      treasureId: 17 }
];

export const ACHIEVEMENTS: Achievement[] = [
  // Tu Tiên (28)
  { id: 'cult_lvl2', title: 'Sơ Nhập Đạo Đồ', category: 'cultivation', icon: '🧘', description: 'Đột phá lên Trúc Cơ Kỳ (Lv.2)', rewardText: '+2 💊 Tụ Linh Đan', reward: { itemId: 'basic', itemAmount: 2 } },
  { id: 'cult_lvl3', title: 'Kết Thành Kim Đan', category: 'cultivation', icon: '🔮', description: 'Độ Kiếp thành công lên Kim Đan Kỳ (Lv.3)', rewardText: '+1 🍃 Hồi Phục Đan', reward: { itemId: 'recover', itemAmount: 1 } },
  { id: 'cult_lvl4', title: 'Nguyên Anh Hội Tụ', category: 'cultivation', icon: '👶', description: 'Đột phá lên Nguyên Anh Kỳ (Lv.4)', rewardText: '+2 🍃 Hồi Phục Đan', reward: { itemId: 'recover', itemAmount: 2 } },
  { id: 'cult_lvl5', title: 'Hóa Thần Xuất S窍', category: 'cultivation', icon: '✨', description: 'Độ Kiếp thành công lên Hóa Thần Kỳ (Lv.5)', rewardText: '+1 🌸 Đại Hoàn Đan', reward: { itemId: 'great', itemAmount: 1 } },
  { id: 'cult_lvl6', title: 'Luyện Hư Nhập Đạo', category: 'cultivation', icon: '🌌', description: 'Độ Kiếp thành công lên Luyện Hư Kỳ (Lv.6)', rewardText: '+1 🌸 Đại Hoàn Đan', reward: { itemId: 'great', itemAmount: 1 } },
  { id: 'cult_lvl7', title: 'Hợp Thể Tam Giới', category: 'cultivation', icon: '⚔️', description: 'Độ Kiếp thành công lên Hợp Thể Kỳ (Lv.7)', rewardText: '+2 🌸 Đại Hoàn Đan', reward: { itemId: 'great', itemAmount: 2 } },
  { id: 'cult_lvl8', title: 'Đại Thừa Viên Viên', category: 'cultivation', icon: '👑', description: 'Độ Kiếp thành công lên Đại Thừa Kỳ (Lv.8)', rewardText: '+1 🔱 Hộ Kiếp Phù', reward: { itemId: 'talisman', itemAmount: 1 } },
  { id: 'cult_lvl9', title: 'Cửu Thiên Độ Kiếp', category: 'cultivation', icon: '⚡', description: 'Độ Kiếp thành công lên Độ Kiếp Kỳ (Lv.9)', rewardText: '+1 🔱 Hộ Kiếp Phù', reward: { itemId: 'talisman', itemAmount: 1 } },
  { id: 'cult_lvl10', title: 'Phi Thăng Chân Tiên', category: 'cultivation', icon: '🌟', description: 'Vượt thiên kiếp phi thăng lên Chân Tiên (Lv.10)', rewardText: '+2 🌸 Đại Hoàn Đan', reward: { itemId: 'great', itemAmount: 2 } },
  { id: 'cult_lvl11', title: 'Huyền Tiên Vô Song', category: 'cultivation', icon: '💫', description: 'Độ Kiếp thành công lên Huyền Tiên (Lv.11)', rewardText: '+2 🌸 Đại Hoàn Đan', reward: { itemId: 'great', itemAmount: 2 } },
  { id: 'cult_lvl12', title: 'Kim Tiên Vạn Thọ', category: 'cultivation', icon: '🏆', description: 'Độ Kiếp thành công lên Kim Tiên (Lv.12)', rewardText: '+2 🔱 Hộ Kiếp Phù', reward: { itemId: 'talisman', itemAmount: 2 } },
  { id: 'cult_lvl13', title: 'Thái Ất Thần Quân', category: 'cultivation', icon: '🏺', description: 'Độ Kiếp thành công lên Thái Ất Ngọc Tiên (Lv.13)', rewardText: '+2 🔱 Hộ Kiếp Phù', reward: { itemId: 'talisman', itemAmount: 2 } },
  { id: 'cult_lvl14', title: 'Thái Ất Vạn Giới', category: 'cultivation', icon: '🔱', description: 'Độ Kiếp thành công lên Thái Ất Kim Tiên (Lv.14)', rewardText: '+3 🌸 Đại Hoàn Đan', reward: { itemId: 'great', itemAmount: 3 } },
  { id: 'cult_lvl15', title: 'Đại La Chí Tôn', category: 'cultivation', icon: '🌌', description: 'Độ Kiếp thành công lên Đại La Kim Tiên (Lv.15)', rewardText: '+3 🔱 Hộ Kiếp Phù', reward: { itemId: 'talisman', itemAmount: 3 } },
  { id: 'cult_lvl16', title: 'Hỗn Nguyên Đạo Tổ', category: 'cultivation', icon: '☯️', description: 'Độ Kiếp thành công lên Hỗn Nguyên Đại La (Lv.16)', rewardText: '+5 🌸 Đại Hoàn Đan', reward: { itemId: 'great', itemAmount: 5 } },
  { id: 'cult_lvl17', title: 'Tiên Đế Chí Tôn', category: 'cultivation', icon: '👑', description: 'Đạt cảnh giới tối cao Thánh Nhân / Tiên Đế (Lv.17)', rewardText: '+5 🔱 Hộ Kiếp Phù', reward: { itemId: 'talisman', itemAmount: 5 } },
  { id: 'cult_xp_500', title: 'Linh Khí Nhập Thể', category: 'cultivation', icon: '💧', description: 'Tích lũy tổng cộng 500 Linh Lực (XP)', rewardText: '+50 XP', reward: { xp: 50 } },
  { id: 'cult_xp_1500', title: 'Khí Hải Trầm Hùng', category: 'cultivation', icon: '🌊', description: 'Tích lũy tổng cộng 1,500 Linh Lực (XP)', rewardText: '+1 🍃 Hồi Phục Đan', reward: { itemId: 'recover', itemAmount: 1 } },
  { id: 'cult_xp_5000', title: 'Đan Điền Mâu Thẫn', category: 'cultivation', icon: '🔮', description: 'Tích lũy tổng cộng 5,000 Linh Lực (XP)', rewardText: '+1 🌸 Đại Hoàn Đan', reward: { itemId: 'great', itemAmount: 1 } },
  { id: 'cult_xp_15000', title: 'Chân Khí Cuồn Cuộn', category: 'cultivation', icon: '💥', description: 'Tích lũy tổng cộng 15,000 Linh Lực (XP)', rewardText: '+2 🌸 Đại Hoàn Đan', reward: { itemId: 'great', itemAmount: 2 } },
  { id: 'cult_xp_40000', title: 'Vô Hạn Linh Mạch', category: 'cultivation', icon: '⚡', description: 'Tích lũy tổng cộng 40,000 Linh Lực (XP)', rewardText: '+1 🔱 Hộ Kiếp Phù', reward: { itemId: 'talisman', itemAmount: 1 } },
  { id: 'cult_xp_100000', title: 'Vạn Cổ Linh Thần', category: 'cultivation', icon: '🔥', description: 'Tích lũy tổng cộng 100,000 Linh Lực (XP)', rewardText: '+3 🔱 Hộ Kiếp Phù', reward: { itemId: 'talisman', itemAmount: 3 } },
  { id: 'cult_break_1', title: 'Kiếp Nạn Lần Đầu', category: 'cultivation', icon: '🌩️', description: 'Độ Kiếp thành công lần đầu tiên', rewardText: '+1 🍃 Hồi Phục Đan', reward: { itemId: 'recover', itemAmount: 1 } },
  { id: 'cult_break_5', title: 'Thiên Lôi Bất Biến', category: 'cultivation', icon: '⚡', description: 'Độ Kiếp thành công 5 lần', rewardText: '+1 🌸 Đại Hoàn Đan', reward: { itemId: 'great', itemAmount: 1 } },
  { id: 'cult_break_10', title: 'Bất Tử Kim Thân', category: 'cultivation', icon: '🛡️', description: 'Độ Kiếp thành công 10 lần', rewardText: '+2 🌸 Đại Hoàn Đan', reward: { itemId: 'great', itemAmount: 2 } },
  { id: 'cult_break_15', title: 'Thiên Đạo Tri Âm', category: 'cultivation', icon: '✨', description: 'Độ Kiếp thành công 15 lần', rewardText: '+2 🔱 Hộ Kiếp Phù', reward: { itemId: 'talisman', itemAmount: 2 } },
  { id: 'cult_fail_3', title: 'Bất Khuất Ý Chí', category: 'cultivation', icon: '🩸', description: 'Nếm trải Độ Kiếp thất bại 3 lần', rewardText: '+3 🍃 Hồi Phục Đan', reward: { itemId: 'recover', itemAmount: 3 } },
  { id: 'cult_pity_trigger', title: 'Tích Tụ Vạn Kiếp', category: 'cultivation', icon: '🕯️', description: 'Nhận được điểm thưởng tích lũy tỉ lệ thất bại (+5% trở lên)', rewardText: '+1 🍃 Hồi Phục Đan', reward: { itemId: 'recover', itemAmount: 1 } },

  // DevOps (26)
  { id: 'dev_1', title: 'Tập Sự DevOps', category: 'devops', icon: '🚀', description: 'Thực hiện 1 lần deploy microservice', rewardText: '+1 🍃 Hồi Phục Đan', reward: { itemId: 'recover', itemAmount: 1 } },
  { id: 'dev_3', title: 'Tác Chiến Khởi Đầu', category: 'devops', icon: '🛰️', description: 'Tích lũy 3 lần deploy microservice', rewardText: '+2 💊 Tụ Linh Đan', reward: { itemId: 'basic', itemAmount: 2 } },
  { id: 'dev_5', title: 'Vận Hành Trơn Tru', category: 'devops', icon: '⚙️', description: 'Tích lũy 5 lần deploy microservice', rewardText: '+1 🍃 Hồi Phục Đan', reward: { itemId: 'recover', itemAmount: 1 } },
  { id: 'dev_10', title: 'Bách Chiến Bách Thắng', category: 'devops', icon: '⚡', description: 'Tích lũy 10 lần deploy microservice', rewardText: '+1 🔱 Hộ Kiếp Phù', reward: { itemId: 'talisman', itemAmount: 1 } },
  { id: 'dev_15', title: 'Tốc Độ Ánh Sáng', category: 'devops', icon: '💨', description: 'Tích lũy 15 lần deploy microservice', rewardText: '+1 🌸 Đại Hoàn Đan', reward: { itemId: 'great', itemAmount: 1 } },
  { id: 'dev_20', title: 'Chuyên Gia Triển Khai', category: 'devops', icon: '🛠️', description: 'Tích lũy 20 lần deploy microservice', rewardText: '+2 🍃 Hồi Phục Đan', reward: { itemId: 'recover', itemAmount: 2 } },
  { id: 'dev_25', title: 'Bán Thần DevOps', category: 'devops', icon: '🔮', description: 'Tích lũy 25 lần deploy microservice', rewardText: '+1 🔱 Hộ Kiếp Phù', reward: { itemId: 'talisman', itemAmount: 1 } },
  { id: 'dev_30', title: 'Kiến Trúc Sư Server', category: 'devops', icon: '🏰', description: 'Tích lũy 30 lần deploy microservice', rewardText: '+2 🌸 Đại Hoàn Đan', reward: { itemId: 'great', itemAmount: 2 } },
  { id: 'dev_40', title: 'Bát Quái Microservices', category: 'devops', icon: '☯️', description: 'Tích lũy 40 lần deploy microservice', rewardText: '+2 🌸 Đại Hoàn Đan', reward: { itemId: 'great', itemAmount: 2 } },
  { id: 'dev_50', title: 'Đại La Deployer', category: 'devops', icon: '⚔️', description: 'Tích lũy 50 lần deploy microservice', rewardText: '+2 🔱 Hộ Kiếp Phù', reward: { itemId: 'talisman', itemAmount: 2 } },
  { id: 'dev_75', title: 'Hư Không Pipeline', category: 'devops', icon: '🌀', description: 'Tích lũy 75 lần deploy microservice', rewardText: '+3 🌸 Đại Hoàn Đan', reward: { itemId: 'great', itemAmount: 3 } },
  { id: 'dev_100', title: 'Thần Cấp DevOps', category: 'devops', icon: '👑', description: 'Tích lũy 100 lần deploy microservice', rewardText: '+3 🔱 Hộ Kiếp Phù', reward: { itemId: 'talisman', itemAmount: 3 } },
  { id: 'dev_150', title: 'Vạn Giới Triển Khai', category: 'devops', icon: '🌌', description: 'Tích lũy 150 lần deploy microservice', rewardText: '+4 🔱 Hộ Kiếp Phù', reward: { itemId: 'talisman', itemAmount: 4 } },
  { id: 'dev_200', title: 'Thánh Nhân Pipeline', category: 'devops', icon: '🌟', description: 'Tích lũy 200 lần deploy microservice', rewardText: '+5 🔱 Hộ Kiếp Phù', reward: { itemId: 'talisman', itemAmount: 5 } },
  { id: 'dev_300', title: 'Vô Địch Cluster', category: 'devops', icon: '💥', description: 'Tích lũy 300 lần deploy microservice', rewardText: '+5 🌸 Đại Hoàn Đan', reward: { itemId: 'great', itemAmount: 5 } },
  { id: 'dev_500', title: 'Chúa Tể Đan Điền Server', category: 'devops', icon: '🔥', description: 'Tích lũy 500 lần deploy microservice', rewardText: '+10 🔱 Hộ Kiếp Phù', reward: { itemId: 'talisman', itemAmount: 10 } },
  { id: 'dev_svc_1', title: 'Độc Hành Khách', category: 'devops', icon: '🌱', description: 'Deploy 1 microservice duy nhất', rewardText: '+1 💊 Tụ Linh Đan', reward: { itemId: 'basic', itemAmount: 1 } },
  { id: 'dev_svc_2', title: 'Song Kiếm Hợp Bích', category: 'devops', icon: '⚔️', description: 'Deploy 2 microservice khác nhau', rewardText: '+1 🍃 Hồi Phục Đan', reward: { itemId: 'recover', itemAmount: 1 } },
  { id: 'dev_svc_3', title: 'Tam Đại Trận Pháp', category: 'devops', icon: '🔺', description: 'Deploy 3 microservice khác nhau', rewardText: '+1 🌸 Đại Hoàn Đan', reward: { itemId: 'great', itemAmount: 1 } },
  { id: 'dev_svc_5', title: 'Ngũ Hành Tụ Hội', category: 'devops', icon: '🖐️', description: 'Deploy 5 microservice khác nhau', rewardText: '+2 🌸 Đại Hoàn Đan', reward: { itemId: 'great', itemAmount: 2 } },
  { id: 'dev_svc_8', title: 'Bát Quái Triển Khai', category: 'devops', icon: '☯️', description: 'Deploy 8 microservice khác nhau', rewardText: '+2 🔱 Hộ Kiếp Phù', reward: { itemId: 'talisman', itemAmount: 2 } },
  { id: 'dev_svc_10', title: 'Vạn Pháp Trở Về', category: 'devops', icon: '👑', description: 'Deploy 10 microservice khác nhau', rewardText: '+3 🔱 Hộ Kiếp Phù', reward: { itemId: 'talisman', itemAmount: 3 } },
  { id: 'dev_multi_2', title: 'Song Hành Xuất Kích', category: 'devops', icon: '⚡', description: 'Multi-deploy 2 microservices đồng thời', rewardText: '+1 🍃 Hồi Phục Đan', reward: { itemId: 'recover', itemAmount: 1 } },
  { id: 'dev_multi_3', title: 'Vạn Giới Đồng Bộ', category: 'devops', icon: '🌌', description: 'Multi-deploy từ 3 microservices trở lên', rewardText: '+2 🌸 Đại Hoàn Đan', reward: { itemId: 'great', itemAmount: 2 } },
  { id: 'dev_multi_4', title: 'Tứ Đại Thiên Vương', category: 'devops', icon: '🛡️', description: 'Multi-deploy từ 4 microservices trở lên', rewardText: '+2 🔱 Hộ Kiếp Phù', reward: { itemId: 'talisman', itemAmount: 2 } },
  { id: 'dev_multi_5', title: 'Vạn Kiếm Quy Tông', category: 'devops', icon: '🗡️', description: 'Multi-deploy từ 5 microservices cùng lúc', rewardText: '+3 🔱 Hộ Kiếp Phù', reward: { itemId: 'talisman', itemAmount: 3 } },

  // Activity (28)
  { id: 'time_5m', title: 'Thanh Tâm Quả Tục', category: 'activity', icon: '🍵', description: 'Tọa thiền online tích lũy đủ 5 phút', rewardText: '+1 💊 Tụ Linh Đan', reward: { itemId: 'basic', itemAmount: 1 } },
  { id: 'time_15m', title: 'Thiền Định Khai Tâm', category: 'activity', icon: '🧘', description: 'Tọa thiền online tích lũy đủ 15 phút', rewardText: '+2 💊 Tụ Linh Đan', reward: { itemId: 'basic', itemAmount: 2 } },
  { id: 'time_30m', title: 'Khí Hải Nguyện Vọng', category: 'activity', icon: '⏳', description: 'Tọa thiền online tích lũy đủ 30 phút', rewardText: '+1 🍃 Hồi Phục Đan', reward: { itemId: 'recover', itemAmount: 1 } },
  { id: 'time_60m', title: 'Khô Thiền Nhất Nguyện', category: 'activity', icon: '⏱️', description: 'Tọa thiền online tích lũy đủ 60 phút', rewardText: '+1 🌸 Đại Hoàn Đan', reward: { itemId: 'great', itemAmount: 1 } },
  { id: 'time_90m', title: 'Tĩnh Tâm Bế Quan', category: 'activity', icon: '🕯️', description: 'Tọa thiền online tích lũy đủ 90 phút', rewardText: '+2 🍃 Hồi Phục Đan', reward: { itemId: 'recover', itemAmount: 2 } },
  { id: 'time_120m', title: 'Linh Thanh Nhập Định', category: 'activity', icon: '🌌', description: 'Tọa thiền online tích lũy đủ 120 phút', rewardText: '+1 🌸 Đại Hoàn Đan', reward: { itemId: 'great', itemAmount: 1 } },
  { id: 'time_180m', title: 'Vạn Vật Tương Thông', category: 'activity', icon: '🔮', description: 'Tọa thiền online tích lũy đủ 180 phút', rewardText: '+2 🌸 Đại Hoàn Đan', reward: { itemId: 'great', itemAmount: 2 } },
  { id: 'time_240m', title: 'Tam Thiên Đại Giới', category: 'activity', icon: '🌐', description: 'Tọa thiền online tích lũy đủ 240 phút', rewardText: '+1 🔱 Hộ Kiếp Phù', reward: { itemId: 'talisman', itemAmount: 1 } },
  { id: 'time_300m', title: 'Vạn Niên Bế Quan', category: 'activity', icon: '🧘‍♂️', description: 'Tọa thiền online tích lũy đủ 300 phút', rewardText: '+2 🔱 Hộ Kiếp Phù', reward: { itemId: 'talisman', itemAmount: 2 } },
  { id: 'time_450m', title: 'Bất Động Như Sơn', category: 'activity', icon: '🏔️', description: 'Tọa thiền online tích lũy đủ 450 phút', rewardText: '+3 🌸 Đại Hoàn Đan', reward: { itemId: 'great', itemAmount: 3 } },
  { id: 'time_600m', title: 'Thiên Địa Trường Thọ', category: 'activity', icon: '🌅', description: 'Tọa thiền online tích lũy đủ 600 phút (10h)', rewardText: '+3 🔱 Hộ Kiếp Phù', reward: { itemId: 'talisman', itemAmount: 3 } },
  { id: 'time_1000m', title: 'Bất Hủ Tu Sĩ', category: 'activity', icon: '💎', description: 'Tọa thiền online tích lũy đủ 1,000 phút', rewardText: '+5 🌸 Đại Hoàn Đan', reward: { itemId: 'great', itemAmount: 5 } },
  { id: 'time_1440m', title: 'Vạn Cổ Trường Sinh', category: 'activity', icon: '🌟', description: 'Tọa thiền online tích lũy đủ 1,440 phút (24h)', rewardText: '+5 🔱 Hộ Kiếp Phù', reward: { itemId: 'talisman', itemAmount: 5 } },
  { id: 'drag_1', title: 'Lần Đầu Bế Thỏ', category: 'activity', icon: '🐰', description: 'Kéo thả Thỏ lần đầu tiên', rewardText: '+1 💊 Tụ Linh Đan', reward: { itemId: 'basic', itemAmount: 1 } },
  { id: 'drag_5', title: 'Thần Hành Phi Hành', category: 'activity', icon: '🎈', description: 'Kéo thả bế Thỏ 5 lần', rewardText: '+2 💊 Tụ Linh Đan', reward: { itemId: 'basic', itemAmount: 2 } },
  { id: 'drag_10', title: 'Khai Thiên Nhất Khiêu', category: 'activity', icon: '🚀', description: 'Kéo thả bế Thỏ 10 lần', rewardText: '+1 🍃 Hồi Phục Đan', reward: { itemId: 'recover', itemAmount: 1 } },
  { id: 'drag_20', title: 'Ngự Kiếm Phi Hành', category: 'activity', icon: '🗡️', description: 'Kéo thả bế Thỏ bay lượn 20 lần', rewardText: '+3 💊 Tụ Linh Đan', reward: { itemId: 'basic', itemAmount: 3 } },
  { id: 'drag_30', title: 'Phiêu Bạt Giang Hồ', category: 'activity', icon: '✨', description: 'Kéo thả bế Thỏ bay lượn 30 lần', rewardText: '+2 🍃 Hồi Phục Đan', reward: { itemId: 'recover', itemAmount: 2 } },
  { id: 'drag_50', title: 'Bồ Đề Du Hý', category: 'activity', icon: '🎡', description: 'Kéo thả bế Thỏ bay lượn 50 lần', rewardText: '+1 🌸 Đại Hoàn Đan', reward: { itemId: 'great', itemAmount: 1 } },
  { id: 'drag_75', title: 'Vân Du Bát Phương', category: 'activity', icon: '☁️', description: 'Kéo thả bế Thỏ bay lượn 75 lần', rewardText: '+2 🌸 Đại Hoàn Đan', reward: { itemId: 'great', itemAmount: 2 } },
  { id: 'drag_100', title: 'Vô Nhất Thố Tiên', category: 'activity', icon: '👑', description: 'Kéo thả bế Thỏ bay lượn 100 lần', rewardText: '+1 🔱 Hộ Kiếp Phù', reward: { itemId: 'talisman', itemAmount: 1 } },
  { id: 'drag_200', title: 'Ngự Thố Tông Master', category: 'activity', icon: '🏆', description: 'Kéo thả bế Thỏ bay lượn 200 lần', rewardText: '+3 🔱 Hộ Kiếp Phù', reward: { itemId: 'talisman', itemAmount: 3 } },
  { id: 'drag_500', title: 'Thần Thố Thượng Cổ', category: 'activity', icon: '🌌', description: 'Kéo thả bế Thỏ bay lượn 500 lần', rewardText: '+5 🔱 Hộ Kiếp Phù', reward: { itemId: 'talisman', itemAmount: 5 } },
  { id: 'pill_1', title: 'Sơ Thử Linh Đan', category: 'activity', icon: '💊', description: 'Cắn 1 viên đan dược đầu tiên', rewardText: '+10 XP', reward: { xp: 10 } },
  { id: 'pill_10', title: 'Đan Dược Khởi Đầu', category: 'activity', icon: '🍃', description: 'Nuốt tổng cộng 10 viên đan dược', rewardText: '+1 🍃 Hồi Phục Đan', reward: { itemId: 'recover', itemAmount: 1 } },
  { id: 'pill_30', title: 'Dược Vương Tái Thế', category: 'activity', icon: '🧪', description: 'Nuốt tổng cộng 30 viên đan dược bất kỳ', rewardText: '+1 🌸 Đại Hoàn Đan', reward: { itemId: 'great', itemAmount: 1 } },
  { id: 'pill_100', title: 'Thần Dược Tông Chủ', category: 'activity', icon: '👑', description: 'Nuốt tổng cộng 100 viên đan dược', rewardText: '+2 🔱 Hộ Kiếp Phù', reward: { itemId: 'talisman', itemAmount: 2 } },
  { id: 'pill_300', title: 'Bách Đan Chi Tôn', category: 'activity', icon: '🔥', description: 'Nuốt tổng cộng 300 viên đan dược', rewardText: '+5 🔱 Hộ Kiếp Phù', reward: { itemId: 'talisman', itemAmount: 5 } },
  { id: 'mount_owner_1', title: 'Ngự Thần Thú Tố', category: 'activity', icon: '🐴', description: 'Sở hữu 1 Thú Cưỡi Tiên Gia đầu tiên', rewardText: '+2 🍃 Hồi Phục Đan', reward: { itemId: 'recover', itemAmount: 2 } },
  { id: 'mount_owner_3', title: 'Tam Đại Linh Thú', category: 'activity', icon: '🐾', description: 'Thu phục đủ 3 Thú Cưỡi Tiên Gia', rewardText: '+1 🌸 Đại Hoàn Đan', reward: { itemId: 'great', itemAmount: 1 } },
  { id: 'mount_owner_5', title: 'Ngũ Hành Thần Thú', category: 'activity', icon: '🌟', description: 'Thu phục đủ 5 Thú Cưỡi Tiên Gia', rewardText: '+2 🌸 Đại Hoàn Đan', reward: { itemId: 'great', itemAmount: 2 } },
  { id: 'mount_owner_10', title: 'Vạn Cổ Ngự Thần Tông', category: 'activity', icon: '👑', description: 'Thu phục trọn bộ 10 Thú Cưỡi Tiên Gia', rewardText: '+3 🔱 Hộ Kiếp Phù & +1,000 Linh Thạch', reward: { itemId: 'talisman', itemAmount: 3 } },
  { id: 'pet_1', title: 'Sơ Thử Vuốt Ve', category: 'activity', icon: '🥰', description: 'Vuốt ve Thỏ Tiên lần đầu tiên', rewardText: '+1 💊 Tụ Linh Đan & +50 💎', reward: { itemId: 'basic', itemAmount: 1 } },
  { id: 'pet_10', title: 'Tiên Tình Thâm Hậu', category: 'activity', icon: '❤️', description: 'Vuốt ve Thỏ Tiên 10 lần', rewardText: '+1 🍃 Hồi Phục Đan', reward: { itemId: 'recover', itemAmount: 1 } },
  { id: 'pet_50', title: 'Linh Thú Tri Âm', category: 'activity', icon: '✨', description: 'Vuốt ve Thỏ Tiên 50 lần', rewardText: '+2 🌸 Đại Hoàn Đan', reward: { itemId: 'great', itemAmount: 2 } },
  { id: 'craft_1', title: 'Luyện Đan Sơ Cấp', category: 'activity', icon: '🧪', description: 'Chế tạo đan dược trong Lò Bát Quái lần đầu tiên', rewardText: '+1 🍃 Hồi Phục Đan', reward: { itemId: 'recover', itemAmount: 1 } },
  { id: 'craft_10', title: 'Dược Tông Đại Sư', category: 'activity', icon: '🔥', description: 'Luyện chế đan dược 10 lần trong Lò Bát Quái', rewardText: '+2 🌸 Đại Hoàn Đan', reward: { itemId: 'great', itemAmount: 2 } },
  { id: 'craft_revive', title: 'Cửu Chuyển Thần Đan', category: 'activity', icon: '🔮', description: 'Luyện thành công Cửu Chuyển Hoàn Hồn Đan cực phẩm', rewardText: '+2 🔱 Hộ Kiếp Phù & +500 💎', reward: { itemId: 'talisman', itemAmount: 2 } },
  { id: 'forge_1', title: 'Rèn Thần Binh', category: 'activity', icon: '🔨', description: 'Nâng cấp Pháp Bảo Hộ Thể lên Cấp 2 lần đầu', rewardText: '+100 💎 Linh Thạch', reward: { spiritStones: 100 } },
  { id: 'forge_talisman_use', title: 'Thần Binh Trợ Lực', category: 'activity', icon: '📜', description: 'Sử dụng Thần Luyện Phù hoặc Bổ Thiên Thạch khi rèn Pháp Bảo lần đầu', rewardText: '+1 📜 Thần Luyện Phù & +100 💎', reward: { itemId: 'forge_talisman', itemAmount: 1, spiritStones: 100 } },
  { id: 'forge_max', title: 'Đại La Pháp Bảo', category: 'activity', icon: '✨', description: 'Nâng cấp 1 Pháp Bảo Hộ Thể lên Cấp 10 Tối Cao', rewardText: '+3 🔱 Hộ Kiếp Phù & +1,000 💎', reward: { itemId: 'talisman', itemAmount: 3 } },

  // Secret (21)
  { id: 'secret_fail_kiep', title: 'Thiên Lôi Thối Thể', category: 'secret', icon: '⚡', description: 'Độ Kiếp thất bại lần đầu tiên', hint: 'Trải qua thử thách sấm sét bất thành...', isSecret: true, rewardText: '+2 🍃 Hồi Phục Đan', reward: { itemId: 'recover', itemAmount: 2 } },
  { id: 'secret_talisman_kiep', title: 'Nghịch Thiên Cải Mệnh', category: 'secret', icon: '🔱', description: 'Độ Kiếp thành công khi đang kích hoạt Hộ Kiếp Phù', hint: 'Dùng pháp bảo huyền thoại trợ lực...', isSecret: true, rewardText: '+1 🌸 Đại Hoàn Đan', reward: { itemId: 'great', itemAmount: 1 } },
  { id: 'secret_night_owl', title: 'Dạ Du Thần Quân', category: 'secret', icon: '🌙', description: 'Deploy hoặc tu luyện khung giờ đêm (23:00 - 05:00)', hint: 'Hấp thu nguyệt hoa lúc nửa đêm...', isSecret: true, rewardText: '+1 🔱 Hộ Kiếp Phù', reward: { itemId: 'talisman', itemAmount: 1 } },
  { id: 'secret_early_bird', title: 'Ninh Sương Chi Tác', category: 'secret', icon: '🌅', description: 'Deploy hoặc tu luyện sáng sớm (05:00 - 07:00)', hint: 'Đón bình minh hấp thụ thái dương khí...', isSecret: true, rewardText: '+1 🌸 Đại Hoàn Đan', reward: { itemId: 'great', itemAmount: 1 } },
  { id: 'secret_noon_master', title: 'Thái Dương Chân Hỏa', category: 'secret', icon: '☀️', description: 'Deploy hoặc tu luyện giữa trưa (12:00 - 13:00)', hint: 'Hấp thu cực dương hỏa khí lúc giữa trưa...', isSecret: true, rewardText: '+1 🌸 Đại Hoàn Đan', reward: { itemId: 'great', itemAmount: 1 } },
  { id: 'secret_first_great_pill', title: 'Cổ Thần Chi Lực', category: 'secret', icon: '🌸', description: 'Nuốt 1 viên Đại Hoàn Đan (+50 XP) lần đầu tiên', hint: 'Thưởng thức linh đan cực phẩm...', isSecret: true, rewardText: '+2 🍃 Hồi Phục Đan', reward: { itemId: 'recover', itemAmount: 2 } },
  { id: 'secret_first_talisman', title: 'Phù Lục Huyền Diệu', category: 'secret', icon: '📜', description: 'Kích hoạt Hộ Kiếp Phù lần đầu tiên', hint: 'Dùng bùa hộ thể bảo vệ kinh mạch...', isSecret: true, rewardText: '+1 🌸 Đại Hoàn Đan', reward: { itemId: 'great', itemAmount: 1 } },
  { id: 'secret_sky_soarer', title: 'Xung Thiên Chi Kính', category: 'secret', icon: '🌌', description: 'Bế Thỏ bay vút lên đỉnh cao nhất trên màn hình', hint: 'Kéo Thỏ bay lên chín tầng mây...', isSecret: true, rewardText: '+2 🍃 Hồi Phục Đan', reward: { itemId: 'recover', itemAmount: 2 } },
  { id: 'secret_ground_roller', title: 'Địa Khí Trầm Hùng', category: 'secret', icon: '🍂', description: 'Bế Thỏ thả sát mặt đất', hint: 'Cho Thỏ tiếp đất sát thương đại địa...', isSecret: true, rewardText: '+1 💊 Tụ Linh Đan', reward: { itemId: 'basic', itemAmount: 1 } },
  { id: 'secret_pill_spree', title: 'Cuồng Đan Chi Thánh', category: 'secret', icon: '💊', description: 'Cắn liên tiếp 5 viên đan dược thần tốc', hint: 'Thưởng thức đan dược liên tục không nghỉ...', isSecret: true, rewardText: '+1 🌸 Đại Hoàn Đan', reward: { itemId: 'great', itemAmount: 1 } },
  { id: 'secret_fail_streak', title: 'Tâm Ma Thối Luyện', category: 'secret', icon: '🔥', description: 'Độ Kiếp thất bại 2 lần liên tiếp tại cùng một cảnh giới', hint: 'Chịu đựng kiếp nạn vạn lần...', isSecret: true, rewardText: '+2 🍃 Hồi Phục Đan', reward: { itemId: 'recover', itemAmount: 2 } },
  { id: 'secret_lucky_break', title: 'Cực Hạn May Mắn', category: 'secret', icon: '🎲', description: 'Độ Kiếp thành công khi tỉ lệ cơ bản cực thấp (<15%)', hint: 'Vượt qua thử thách với tỉ lệ mong manh...', isSecret: true, rewardText: '+2 🔱 Hộ Kiếp Phù', reward: { itemId: 'talisman', itemAmount: 2 } },
  { id: 'secret_pity_god', title: 'Tích Khí Vận Hoàng Đế', category: 'secret', icon: '👑', description: 'Độ Kiếp thành công khi điểm tích lũy thất bại đạt +15% trở lên', hint: 'Dùng kiên trì tích lũy khí vận...', isSecret: true, rewardText: '+2 🔱 Hộ Kiếp Phù', reward: { itemId: 'talisman', itemAmount: 2 } },
  { id: 'secret_treasure_master', title: 'Đại Pháp Bảo Sư', category: 'secret', icon: '🔮', description: 'Mở khóa 5 Pháp Bảo Hộ Thể', hint: 'Thu thập đủ 5 bảo vật hộ thân...', isSecret: true, rewardText: '+1 🌸 Đại Hoàn Đan', reward: { itemId: 'great', itemAmount: 1 } },
  { id: 'secret_skin_collector', title: 'Bách Biến Thân Pháp', category: 'secret', icon: '🥋', description: 'Mở khóa 5 Thân Pháp / Skin Thỏ', hint: 'Sở hữu 5 trang phục cảnh giới...', isSecret: true, rewardText: '+1 🌸 Đại Hoàn Đan', reward: { itemId: 'great', itemAmount: 1 } },
  { id: 'secret_full_inventory', title: 'Tiên Gia Bảo Kho', category: 'secret', icon: '🎒', description: 'Tích trữ tổng cộng 20+ viên đan dược trong túi', hint: 'Sở hữu kho đan dược dạt dào...', isSecret: true, rewardText: '+1 🔱 Hộ Kiếp Phù', reward: { itemId: 'talisman', itemAmount: 1 } },
  { id: 'secret_multi_deploy_master', title: 'Vạn Giới Triệu Hồi', category: 'secret', icon: '🌌', description: 'Thực hiện 3 lần Multi-Deploy', hint: 'Điều khiển đồng thời nhiều đại trận 3 lần...', isSecret: true, rewardText: '+2 🌸 Đại Hoàn Đan', reward: { itemId: 'great', itemAmount: 2 } },
  { id: 'secret_marathon', title: 'Bất Tĩnh Bế Quan', category: 'secret', icon: '🧘‍♀️', description: 'Bế quan liên tục trong phiên làm việc đủ 100 phút', hint: 'Thiền định trong 1 phiên lâu dài...', isSecret: true, rewardText: '+2 🌸 Đại Hoàn Đan', reward: { itemId: 'great', itemAmount: 2 } },
  { id: 'secret_devops_guru', title: 'DevOps Đạo Tổ', category: 'secret', icon: '⚔️', description: 'Tích lũy 30 lần deploy thành công', hint: 'Trở thành huyền thoại triển khai...', isSecret: true, rewardText: '+2 🔱 Hộ Kiếp Phù', reward: { itemId: 'talisman', itemAmount: 2 } },
  { id: 'secret_mount_supreme', title: 'Thượng Cổ Thần Phục', category: 'secret', icon: '🐉', description: 'Sở hữu Thú Cưỡi phẩm Supreme (Bạch Ngọc Kỳ Lân hoặc Cửu Thiên Lôi Long)', hint: 'Thu phục thần thú tối cao phẩm Supreme...', isSecret: true, rewardText: '+2 🔱 Hộ Kiếp Phù', reward: { itemId: 'talisman', itemAmount: 2 } },
  { id: 'secret_mount_gacha_5', title: 'Bí Cảnh Linh Thú', category: 'secret', icon: '🔮', description: 'Quay Gacha Rương Linh Thú tích lũy đủ 5 lần', hint: 'Khám phá bí cảnh Linh Thú 5 lần...', isSecret: true, rewardText: '+200 Linh Thạch', reward: { spiritStones: 200 } },
  { id: 'secret_pet_100', title: 'Thần Thố Sủng Ái', category: 'secret', icon: '👑', description: 'Vuốt ve Thỏ Tiên 100 lần', hint: 'Bày tỏ tình cảm vuốt ve Thỏ 100 lần...', isSecret: true, rewardText: '+2 🔱 Hộ Kiếp Phù & +500 💎', reward: { itemId: 'talisman', itemAmount: 2 } },
  { id: 'secret_craft_god', title: 'Đạo Tổ Luyện Đan', category: 'secret', icon: '👑', description: 'Luyện chế đan dược 50 lần trong Lò Bát Quái', hint: 'Khái niệm Luyện Đan Tông Sư 50 lần...', isSecret: true, rewardText: '+5 🔱 Hộ Kiếp Phù & +2,000 💎', reward: { itemId: 'talisman', itemAmount: 5 } },
  { id: 'craft_fail_1', title: '💥 Nổ Lò Sơ Cấp', category: 'activity', icon: '💥', description: 'Luyện đan thất bại bị nổ lò 1 lần', rewardText: '+1 💊 Tụ Linh Đan', reward: { itemId: 'basic', itemAmount: 1 } },
  { id: 'craft_fail_5', title: '💣 Đạo Tổ Nổ Lò', category: 'activity', icon: '💣', description: 'Luyện đan thất bại bị nổ lò 5 lần', rewardText: '+2 🍃 Hồi Phục Đan', reward: { itemId: 'recover', itemAmount: 2 } },
  { id: 'secret_forge_fail', title: '🌩️ Lôi Kiếp Rèn Thần Binh', category: 'secret', icon: '⚡', description: 'Rèn Pháp Bảo thất bại do lôi điện bạo tạc 1 lần', hint: 'Thử thách độ may mắn khi rèn thần binh...', isSecret: true, rewardText: '+50 💎 Linh Thạch', reward: { spiritStones: 50 } },
  { id: 'forge_buff_success', title: 'Thiên Công Xảo Đoạt', category: 'secret', icon: '✨', description: 'Rèn Pháp Bảo thành công khi có phụ trợ của Thần Luyện Phù / Bổ Thiên Thạch', hint: 'Dùng bùa rèn tôi luyện thần binh thành công...', isSecret: true, rewardText: '+1 💠 Bổ Thiên Thạch & +200 💎', reward: { itemId: 'sky_stone', itemAmount: 1, spiritStones: 200 } },
  { id: 'secret_supreme_immortal', title: 'Độc Tôn Tam Giới', category: 'secret', icon: '🏆', description: 'Mở khóa hơn 50 thành tựu các loại', hint: 'Chinh phục hơn nửa chặng đường thành tựu...', isSecret: true, rewardText: '+5 🔱 Hộ Kiếp Phù', reward: { itemId: 'talisman', itemAmount: 5 } }
];
